language: python
python:
- '2.7'
notifications:
  email:
  - tang.jilong@gmail.com
install:
- pip install virtualenv
before_script:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- echo 'Setup test environment.'
- cd /home/travis/build/cogenda/cloud-sync
- ./setenv.sh
- source venv/bin/activate
#- echo 'Ready to static code verification.'
#- make pylint
#- echo 'Ready to run tests.'
#- make test
after_success:
- echo 'Ready to deploy cogenda web distro to Lindo server.'
- make deploy
branches:
  only:
  - master
env:
  global:
  -secure: "h6VeDGgTtIGetahIslv2J55FSAA08gwtFuzGwRhjKeC/NT7Jy/e7HfRKDLcw2bpiIccmHPSiTuZSjlOcoDZXElzVo/h3XNNxUNDBTC+UKHGotVIpf38brggp5ko//mpEh/hvf3OQuMFSbanmf9F4BbjDOI6u/VXEbS0405Eym4E="
  -secure: "XVNCsMe30bwkVclP2fm731In1/66piUk4oITmuerxFUpz4SgraZlj2WCU/WBQkpkxnlzBJeOmP4td1d5hDcqWvNSLFgJ7o6qYP8mEGTOLQWDF+QqUlgPMK9ZMxsJXtG+FskNbj2BSD8PNZOwDDS/FTVceyE7+IrTC6hgonpmvmg="
  -secure: "bUMnliKTMcLKHu1Znh4n2DpP1xE167F75TD8XznW5AkeVgT4Bjw5kSwVJNSyA4Utzj5h9eaBRUVhNIC5HOCiWa3JPzqu8hHgAME1+RCypihjENjk8i+ccqxhufVnUDat/0xMN45RoNaJNFmmkwBadGzSS/H931YSXhkHyttSBig="
  -secure: "W5jvP8dzaaTVOfS1j1gkMt1LE7QX2ZhUAQM4QV8LQiId0fB/xyIyL64QG2WMDXYIbGUxY9avQHKQQfmPf01uKztgYndzqphLxo/g2iocNhqWMjxBu0me27jZorMfc7iYj0dw1BWliXEazmvpyl7Yr+FW4cKO+8icChqki2Er+Gs="
  -secure: "Dxpfr5QHPAJoX7sKO9eUomj9X0+Vgk2aY1wYy1cg2FnSyOFAbX16guK7qGdmn+U3d/kItfbby3hSWXGAcZiKGC0y58Ei5968GBw7e8l311VJqT8RzyTvS6CMTh2GlP9nCiwaW0MIspiRQToY+CZ/Mk8416y26K3tZ0pyjeUyS/c="
  -secure: "CKZVhhha8y9Cugg48fZ3fgliLAdwFN1ahPUfZEDYgTwltB7yXRNX+FVOKk2PiD7MtQTwzy1/5hyYrSEFeIQW880j1kBgsdRy/2heOIW6xSmnyg+3Etg/EjFqDGWBu4pbyszQwunIj2r7V4fM3Z+nkZfyO9UDnu7wiya7WR+BYhQ="
  -secure: "H/3izuwd3xgkwSXdL6tyT5eguYrazpgz9VM/YAdWBleQxwPPxtzRYvrzUxjBxHHC2Kk0RqIobqQCkOOnFSwrs/UXVAi3bM1i0yvqv8/EBPk64M7vnek0CyuGOi6CvubOCcthy69mQxFRvO54JxiYUYDVYYv7k6k4Yre4Gi8IHWc="
  -secure: "W3EqOSkcbx8cY1g4cg4iLp5kbqf17wxWsmj+kAWFz8ZlWCf6XX4gc8wgnmcCEaGq2/oW6Bcnzy1L3GjVeCW+78b7MOyWmQJvda+YabSfM3ARj4pnoI0kLnGu2Zz69p7ImRZmgf+g1WcAohdq9Xfk0kalinbqyq/lDp9DGOXbhUg="
  -secure: "aTQMEwWKUvEXjFpDQCtp35yFCXce69LXiznU+HD9GREqqVghBAc0eVbiGejDSYjjJc17jmvVuSuhn/FlTimkKRzR1ylfuEXO1NO8ZSYCLVgArppt1u0aDu+DDlHFczzW6UDLUOODB+kJ6EFBRjZlukiTNo0U0R6UZOLAOKq+jC0="
  -secure: "dY5iijf20KMzUR0kFM2s8KKKApCDea6eU4mVaCNNPij7s02YliNhzKOx/F9h0ViHtntPaVyI/qysl8TozwIDrIuPAIwh2aRtWjoxfFHOWwFa2AUH3n4KGISXrlqiOiTVRr77xU1UXMDUiD1KwgKIxiGSb16SdjoZXJT1lVmBC74="
  -secure: "DsWyY0eQIckkbroG5eLBXCgzQgo2cfV2TOSxN+DCqZspOy1ujVvW86DiLqiqTYGaScuDotzW8O74dfsPd05ETeJpAl67MbP0USRMD1nHHodFYoGYzwiaDIskBQbF+egqX+P1ElFcWiXkav8DruJDGY7jqQulOFzgB15zmsc/cos="
  -secure: "hkJJHgu21/EjrBm5bn2V44yrMdt14pdq8RCUWb4t1SuzQhOK7eRK3SDqge3lCFM4+pWbfjacyBdQdQVlqXpwOn/BR0EzlAXMT94OUYXz75k9aLq7iHJ1gvjX0Y0xLIc0wHSnGTvLOJQmi7tvF0AoFiiT3hn9oq+g4jfpEb3+Qak="
  -secure: "e5J5CiKyDOsrslKlwmbMLsVDs/rK0b8ZSFFTtGZQ0WqpHZJJfnZa0l1jlCkW942EOuoe0DnsC3nd0kwpSeVttZoK5toda/rB4LdrIoKMvfaT70J/ge+gR0WXLBLUsB3RPEv0SHpqRjfT5pT1G9iQQ0klZYx11/+bsK6nPZ/XxP8="
  -secure: "PGsatACul2/tWl8mARHw0rttKCHE6jfVXutH7ia0GwiEqSm/BEFKup/LPOOcCtowbMX8LeFnHk32PyLqjxL9P2MeJRuN1CMdfaS69hZ3tSQ+ofeR90WlK9W0/vjscoKn9jWTB8ANLowO7NgQs0p/mxxpc6yV2zdiF8hZzkSgxAM="
  -secure: "GA4oyNKqsXZ8YNGTPeArg6wfPJXsI1eIn5XzJynOPvILl5HPfF45yQK6RlVe9qvZhb2gu03whQkKIo37oyO363/lfHxGzOc2kaqzQU2RKUViKBCTkj+iMmDPQ3fTW6OAtpIYRV6loT4MJZXHHD77637XSuuBJg5+WlUlTcD3rDc="
  -secure: "AvDTmaptDESLJqtPQGrH4S7ac0FOJY8MlKJnNwIBUW8RANadZBSwX0vE0mHsGA0PKXrQ6x5CZ5gsC4nZObtdxEZC0rSY4OTeuLgGyzFwLXwkw2WAiz3xyTnSBPcHNu7QSroaiyFs5dE8zq/IAbe5PFnAX7g5CzgWyXQOSuhQPFI="
  -secure: "eCKVCNWNKzf7SOyCBdud2vLgCqW+02TtVLsGiUkt5dcNzbqfU+f2yLV40Rk+FG9IUUeAjthPgJ7FaKb6OkJhkcBLl94HXSgKcsaM7EU9mm4aPBpd0E9nYhulwTS9D9rlOCXpvmgvKYnGpSXxU0Omt1lMk7YpZkrXP5bhn6kvV6M="
  -secure: "IVrIdcKSfb5BgHYeNkke+NMDSNtWXmYR2TsSNE8c1thQAjH0hwwj3AJBrEON0IATzXXbt1Z3B1VcUvrCK6ZtajQxVmzcMiA5IbRkiUHWE9G3wt1eKGqygF6lHVsXv47rinFHGrpw0U24Q5OacYxMVrhoCWEQdNRWcPSQWbYbUm8="
  -secure: "hhywPGlqEgtdraOM+78CLpEeocVsHcYcuj/Psr5RWpcq3BRemsJe2QYWWLTc4JPUW7m2YmQcnanWqk292XllWK8VWMUQO1gDnb0p9ERMve8uqT34cYlCsWP0MwNqI2rxpTadXwXRbzkNIGfEKRCigZqlwlapZrwocWA6SBHkC3c="
  -secure: "LQojnUKbUyN0onbbqvjRkox9mo/al+454fEKHHipY146WD94keFTs+F/7jjR+51/wcGktklQD+QPpsnF6GViA1lMsmt2ixEZji3tByYbEhF9ZScErfzbnRZFaqcPIEJTv12vyXDzzkJYoN/Sw2IbybOqu6MCoQb5s2qu/tCXl5s="
  -secure: "XMwOFJCkGjWA6OjawwTXXB1x413FWYJVMmA6GfovY521KlsSaeHtvpGApnXh+6o+0qehvX13mPQiP1/LmOtieg2XZno1v/tXj6ujg8YkU3BVFiW4BqhEUj9chF5PMii9u5mdBNYx01cMZb5q92D9UFbZwSBxhAxG9swGSLu8IC8="
  -secure: "CgwCj7Km2cgp51pLQS1cf8uecqEkb/SdiERVWkD39BSVUvdqwVf+CUWkFBwoU4qQ04mgvY6sAw9dDqdQrrg0xHx5+SSrXCH7yaE4O0wiCx5huv/XksccCuDvAlaZvMGV4GVDnnvJA0NzfFWgaZ+/82Xo41OJrIlgiLz2Gp4ogX8="
  -secure: "Nm5dhKbr8GsBndCizGiq+mMvlC37nje+oXBQMiV1szByBKcFcPr1L+bmsLx2+ojvDkBiBCjqvk37oiWVAnNj0q4N2a2ozZHMk6NxgTq4wlEv2HRlHC9lOQJbLvgNN17RknddQS6rjbQ0Q9gWcdt8seok7s1zoWynK9YVw5JAb5A="