language: python
python:
- '2.7'
notifications:
  email:
  - tang.jilong@gmail.com
install:
- pip install virtualenv
before_script:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- echo 'Setup test environment.'
- cd /home/travis/build/cogenda/cloud-sync
- ./setenv.sh
- source venv/bin/activate
#- echo 'Ready to static code verification.'
#- make pylint
#- echo 'Ready to run tests.'
#- make test
after_success:
- echo 'Ready to deploy cogenda web distro to Lindo server.'
- make deploy
branches:
  only:
  - master
env:
  global:
      - secure: "fIrd55jZUIYzyLglLCUk9LWfnJc64aFMYzLDOWxJ+530TklK5FQ4jD8Bjalg1xgAOsXONHIg38cgF8sQzkcjQo+t1IFmpH12qgiVYJ//+m9WOrBstOYMWkekoliejOqm+N3kla+Q6ga3/9Pgzd+uPEF/LgFgD01rs1WmrJ7KfnQ="
      - secure: "hFRq8wCB8pCeNyE4tOx86nMV7WnJ6Va36PRx5CRjlqLj6vNn/bKiadwRrOrX0XBMLFMue1Iaf4Tce7IDwOnkQwkDpEA0nqwGEFB/4F8SMR8qLc85veA/ViIY//twTsY0Ps5RIn8C/VU/5IZiyNQXp9Ixd0Kmrodz8WcFvGufXis="
      - secure: "CopmY077c84kP6dZKhenx+Ga5HLy3tbI9afPoZFsHTgnCY2ro7fl+Gs0BvKHqHHp1rPFgm/XKWKVxqVolC/V2JAep00b6CAuHtLpzwI5dkSoWkr+8WvqI/ht1ID9Q/OQB3tmkxVi7humBIUg1sG+aBLUeRS9x+kjIdg1t2zheYM="
      - secure: "Z0icESentxTpUINwNxAINTbkqvzhzcWfg0sYye9gQXDWzngjgg3u6PEIoPxpruBAI4y1o8ArrM9gnc4by8UHuEocay33fBR7yHsp9aCzvp7YYMep2N0S1njfuNzpc7Th1jDoYoyRlCVuEUuTQHBLIlybf0ADpxP4MUVQGuM75FI="
      - secure: "fDWuKP3KvpL9lbgG95YPcaHB4gZxY67aZ2voBxYcjN3iZNCWHRD5Vt0fzdYTHemO548CHvHQFl8E+SIJt7eAyJKkE1IkyuHOiuT+fHFyKBz+BD7su0DMYM80+4hnb67cg1CtfhQGppcMB1113ZGcbRaRMSWCwFSna18DBa4GkV0="
      - secure: "Lo8KfURjh38JdfO5FdjaJfThY/OGbFEANmgBojadlpwrq9OwZHstt0yTGlM/nZ+yaEXDmt4s3Px2eWkF41CF8lNwoguUQxp5maSxjleES+5uUC4EkxfqWwdOrPMB4XJeJKnLPk6gcOzRjxQZGX+xKA6XTljJerSFHbyii05gjr4="
      - secure: "PndHIs9ielL9GKrwbRNaqpjOnRcNTxyS4ShmDAr/SQpFvnt0MB1fdfru7dqs/y5qv8N/5cnAEZZ0HKumXfL7iV/S5tLUZhtv7KqwfsUnobdGC/eG1QIsx1O2Emz7pJXjZ8rJmo/jQIigwmah4TUuYExKx7fErlLvbhaIeLztzU4="
      - secure: "h8rZSixi54nw4DtfCocCuqW/J3olKS9d4rxwz4BOsMrmfQLs2FB0zPtFAZTff/y2v8cury8aNtUUzOv2ph+puZiRicJDU3ld/EMz1EMUiTb/lrrBBDXtpw8zBr6M57Jc17uiTBskyrp9kHsvFVE2BG0ITOAVlRFNaxQJXDdP0Jo="
      - secure: "QjknmCVCG4hv9xiswH3zJd2z+YVyHMXxRkCDwGKGBJH5bcZ1fRgoMg8c6BnwBN7hYlIDqPxjDL2IO0HAh0mQJv9A40Cgc6y99znPhUnWtaaEClEdAFLahEI9PG75tqdNkUvJipcwFY2Ic18CBISYYJBQQiZVOOJE7mD1wj5HkZk="
      - secure: "Cr2kNr3aeZuRwlAP4v2I4LT6moj/pyLLsun7ZoWhcpvep91aWWRBRhSz3SYfvx76QSxUhuDP3/DhQ50VqDP9nn5/HXCM4x0oocu1aTzVUZtYicVGNzmweBFmSw6lS7DJFTcosnmHgOkz9mqMae9PAK/j37co0y/NF4Yr7zmH7rU="
      - secure: "YT89cHTJlY+z0EyewkEKVPQpqE3bNJtAa7G1Q0dR8RcnZftESpLNP2vTiADnZhaWX/MsRlZOP8hDaaxe4g3B7MZIFM+X/a4JzjG98ehsqpRodSfaNejL1E35htoAIHA+q+/UN2RaEq52yCaVepVwToQ5Mv/laVtIIkMPd9QY/RQ="
      - secure: "Uu2aoJUEJ2kFBINQyOguZcdozP2FenLSU1V8BjuYHGVIXyQZKxfY7JCX9vcnJeaXDzc+Lin0H5bIyGsQSf/n8y3b41n4Jtap6li1IM9vBIdOtDNjaY6qW4jep0753EIEBdWR92tAn/Cn5UqRZvvYBYTmf7TywhgUlFxdW+OeWus="
      - secure: "BtHRLLoir3/rt43pauhWxSMEeGw5dvFv2Yv8uJh5IHcevCjRy8YHKLmHFjVeih0rLS0zLRJaov5VoH8nJIvkWEy6ZVGEoHZlMXxncvbrrmCZj6AGp+p0UUFp6JccFhuTGPBlwtx1F2Ayfm3kjJZ7DZZaTdWpzD5727JP/UVMTug="
      - secure: "WbOG3babRGjclIo/i/hYowdYS3grwNcIt6unWGawxXLhkb44fRPwIf38nXYpFSCPaYdhyUzVEB61HLRb5JpPaTJa78Sa1JcrQQ8NY7xZCAksmYGyFo+efbL8XOWh9+Ck2yqTV/4lAFiWlBYSRfpqn3yCblg3+zXb0btFC09EP4w="
      - secure: "bRzOW3Qclx8HDCzynW6Zqn+B71mImAtf3IY+k2/uijcZvUxNHM82y0zEz3udlc1xlnXJUFfBx5qiCe3kgcwSHI4/OLqK9NYKFhqtcAHJoADIJvEP4kkmBvGYMiFG8L3yYC07f5duClKirFJTZD51WSPMo4sRhhy+2rS0ixQJD1M="
      - secure: "KxkiTaEfNSUTUSSRnRfVhkdpgTb58DpJyvh7mnY6cw4kKMbbbqmalt53JFZv2WPqUtpvMzdhVuOfw4ECcsBsDg68hq9xK0dbDB79/ZW9k764oZZachhw8RgpE0Nbxny3hNXXljoX8F7gSE/mDhqzX/54wZzB1VOsCR5gC6VBLRw="
      - secure: "VAd6QsY4BdYx7Uwy6prwAxXvRJsV8uXDDAT7zmAIBtzV5o99ugQ6WUNYxYLnIwoupbaaj7I1+DXb3YkN0DcL+2koV6nqHIp+dJZEW40rdz2A57LmykknVkrb7M64j+gVhOdye3xPTm/9xH2C2iZPwCglxJFjcyMxCNXlH3fLQnQ="
      - secure: "RveDj5ZLshSTiXhyw1MoZwRlD4CqeTjFOhqUpPevHmZhhxCT8amaqc1aVNf0MHBkmJVy1V55l9QdWDBbhUREKPTOrO4vsq5c5+R7CRGnGj/6vzujd+xz5i2jsH9k3dinwlJ2tzpQ8/0O3+X9O4ILJvImRNZYSti6OCKggqPD8Ls="
      - secure: "Nj6x5D5OHU0LgB+CsaqS5Z6CbPX4DkOCiDzc5/BoAmPWy9Mx8LKJTEuiPe9L5ly7cTwUgFwmo/z4zEzt0oB1CmPT7x6zD6MSEvzM5jCoigZhO6/wcGVt1YKYhCPG7n+jsJ8axhpyWWx7ttWDX6naqAlWXMmSmGeyFlTQsXLLwM8="
      - secure: "HtZVdsiMKFWvww4h2+o0QR1f61bNe1mqyQgbDpdZEMgJpvcWeTnGjMdnqxpGegPCUewwysCoAv5ouZFrCsJal+vaSawYWxbWGysKWAIfT3OTP4MIZvWsv0XgecqGnslae9RDvs17XJsi6HtNQY2ZDdNIEiXB1iq8sCpX5IWTP4s="
      - secure: "WkvHyAhq9p58LDDrGuSFindGA4orbdfRucqucdhV73k7xrTlrIm7dJfE0SWOjab7F+MGELsZ3Kfo1Yege9gOq9CiqFYxWor9BXpA1ixXLlMKJ3V4M5LaNyOuGepHBCd3+jEwxlDocJ+/HrELtE+hrCQJop8Tw3V8eKLRt7qqsG4="
      - secure: "frhYsTuxaomSX6seIr5i+EjUy3MSSYRz99c8bam8tVDYq5EjQqhusQIJxu2QaYb0IgV27e3C0H7LY7t7+gev5USK5qOVpE9x1jYOdBQci5+h3cMyG8sfqursD4cGGWdCpks2YavnI+wwwXVlcZ2JTL/lp3YDDffve5SKZfEQNOo="
      - secure: "N4qYaN2Iyg8XKRL3UirsJljdgqYf9f9IxeoGvL8lHW92dzqShZWtrm0xX3QICRr80RyNt9rusk2ZZ49d8hdLRLpMvRZPOq6ShqlaJ7GSeiSVadaPmNVApygIbTkz2oKGmnGcKdiA5/VugxCDlc3JAi/qMYIVkcm1wJHIZOFeC1g="
